### ISSUE TITLE
Spamming hammer and sicke desyncs animation and buffers hits

### ISSUE THREAD

**Issue by UltraBlackLinux** [mammal-is-fleshy/ARC9-CSS#1]
Hey there,
I just noticed that spamclicking the hammer and sicke item leads to animation desyncs and buffered hits (the latter meaning that even after I let go of the mouse button it sometimes still hits): https://chonkyrabbit.eu/filebin/r/29jrCkVh0f#Ru+uJcu24zrn9g0bzboLCuuEd43Paa0labC/XUKB0Wc=
Please fix this!
Thanks

**Comment by mammal-is-fleshy** [comment]
blame arctic for his shit coding

**Comment by UltraBlackLinux** [comment]
Well I would just open an issue over at arc9, but you have to tell me what's wrong before I can do that (or you just open one)
